/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ptit.view.linhkien;

import com.ptit.dao.LinhKienDAO;
import com.ptit.model.HoadonLinhkien;
import com.ptit.model.LinhKien;
import com.ptit.model.NhaCungCap;
import com.ptit.model.Nhanvien;
import com.ptit.view.hoadon.HoaDonView;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TUNGND
 */
public class SearchLinhKienView extends javax.swing.JFrame {

    Nhanvien nhanvien;
    NhaCungCap nhaCungCap;
    List<LinhKien> list;
    LinhKienDAO linhKienDAO;
    List<HoadonLinhkien> slist;
    LinhKien selected;

    /**
     * Creates new form SearchCustomerView
     */
    public SearchLinhKienView(Nhanvien nv, NhaCungCap ncc, List<HoadonLinhkien> listHoadonLinhkien) {
        initComponents();
        showXacNhan(false);
        nhanvien = nv;
        linhKienDAO = new LinhKienDAO();
        nhaCungCap = ncc;
        slist = listHoadonLinhkien;

        getLinhKien("");

        this.setLocationRelativeTo(null);
    }

    private void showXacNhan(boolean b) {
        this.jLabelLKMa.setVisible(b);
        this.jLabelDonGia.setVisible(b);
        this.jTextFieldDonGia.setVisible(b);
        this.jLabelSoLuong.setVisible(b);
        this.jTextFieldSoLuong.setVisible(b);
        this.jButtonConfirm.setVisible(b);
        this.jLabelLKMa.setVisible(b);
        this.jLabelGetLSMa.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTenLinhKien = new javax.swing.JLabel();
        jTextFieldTenLinhKien = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDSLK = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelLKMa = new javax.swing.JLabel();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jLabelSoLuong = new javax.swing.JLabel();
        jTextFieldDonGia = new javax.swing.JTextField();
        jButtonConfirm = new javax.swing.JButton();
        jLabelDonGia = new javax.swing.JLabel();
        jLabelGetLSMa = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTenLinhKien.setText("Nhập tên linh kiện");

        jButtonSearch.setText("Tìm kiếm");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTableDSLK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Hãng", "Đơn vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDSLK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDSLKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDSLK);
        if (jTableDSLK.getColumnModel().getColumnCount() > 0) {
            jTableDSLK.getColumnModel().getColumn(0).setResizable(false);
            jTableDSLK.getColumnModel().getColumn(1).setResizable(false);
            jTableDSLK.getColumnModel().getColumn(2).setResizable(false);
            jTableDSLK.getColumnModel().getColumn(3).setResizable(false);
        }

        jButtonAdd.setText("Thêm mới");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonBack.setText("Quay lại");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelLKMa.setText("Linh kiện:");

        jLabelSoLuong.setText("Số lượng");

        jButtonConfirm.setText("Xác nhận");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jLabelDonGia.setText("Đơn giá");

        jLabelGetLSMa.setText("lk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTenLinhKien)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTenLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBack)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelLKMa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelGetLSMa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDonGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelSoLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirm)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTenLinhKien)
                    .addComponent(jTextFieldTenLinhKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonBack))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLKMa)
                    .addComponent(jTextFieldSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSoLuong)
                    .addComponent(jTextFieldDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConfirm)
                    .addComponent(jLabelDonGia)
                    .addComponent(jLabelGetLSMa))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        showXacNhan(false);
        String key = jTextFieldTenLinhKien.getText();
        getLinhKien(key);
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void getLinhKien(String key) {
        list = linhKienDAO.getLinhKien(nhaCungCap.getID(), key);
        DefaultTableModel model = (DefaultTableModel) this.jTableDSLK.getModel();
        model.setRowCount(0);
        if (list.isEmpty()) {
            if (key.isEmpty()) {

            } else {
                model.addRow(new Object[]{
                    "Không có dữ liệu", "", "", ""});
            }
        } else {
            for (LinhKien linhKien : list) {
                model.addRow(new Object[]{
                    linhKien.getMa(), linhKien.getTen(), linhKien.getHang(), linhKien.getDonVi()
                });
            }
        }
    }

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddLinhKienView addLinhKienView = new AddLinhKienView(nhanvien, nhaCungCap, slist);
        addLinhKienView.setVisible(true);
        addLinhKienView.setTitle("Thêm mới linh kiện");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jTableDSLKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDSLKMouseClicked
        // TODO add your handling code here:   
        if (list.isEmpty()) {
        } else {
            showXacNhan(true);
            int index = jTableDSLK.getSelectedRow();
            selected = list.get(index);
            this.jLabelGetLSMa.setText(selected.getMa());
        }
    }//GEN-LAST:event_jTableDSLKMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HoaDonView hoaDonView = new HoaDonView(nhanvien, nhaCungCap, slist);
        hoaDonView.setVisible(true);
        hoaDonView.setTitle("Thông tin hoá đơn");
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
        int validate = 0;
        Float donGia = 0.0f;
        int soLuong = 0;
        try {
            donGia = Float.parseFloat(jTextFieldDonGia.getText());
            soLuong = Integer.parseInt(jTextFieldSoLuong.getText());
            if (donGia > 0 && soLuong > 0) {
                validate = 1;
            } else {
                JOptionPane.showMessageDialog(this, "Đơn giá và số lượng phải lớn hơn 0");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Đơn giá và số lượng phải là số");
        }
        if (validate == 1) {
            int i = 0;
            int index = -1;
            for (HoadonLinhkien element : slist) {
                if (Objects.equals((element.getLinhKien()).getMa(), selected.getMa())) {
                    index = i;
                }
                i += 1;
            }
            if (index != -1) {
                slist.remove(index);
            }
            HoadonLinhkien item = new HoadonLinhkien();
            LinhKien linhKien = new LinhKien();
            linhKien.setID(selected.getID());
            linhKien.setMa(selected.getMa());
            linhKien.setTen(selected.getTen());
            linhKien.setHang(selected.getHang());
            item.setDonGia(donGia);
            item.setSoLuong(soLuong);
            item.setThanhTien(donGia * soLuong);
            item.setLinhKien(linhKien);
            slist.add(item);
            this.setVisible(false);
            HoaDonView hoaDonView = new HoaDonView(nhanvien, nhaCungCap, slist);
            hoaDonView.setVisible(true);
            hoaDonView.setTitle("Thông tin hoá đơn");
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchLinhKienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchLinhKienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchLinhKienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchLinhKienView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchLinhKienView(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelDonGia;
    private javax.swing.JLabel jLabelGetLSMa;
    private javax.swing.JLabel jLabelLKMa;
    private javax.swing.JLabel jLabelSoLuong;
    private javax.swing.JLabel jLabelTenLinhKien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDSLK;
    private javax.swing.JTextField jTextFieldDonGia;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTenLinhKien;
    // End of variables declaration//GEN-END:variables
}
