/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ptit.view;

import com.ptit.dao.HoaDonDAO;
import com.ptit.model.HoadonLinhkien;
import com.ptit.model.NhaCungCap;
import com.ptit.model.Nhanvien;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

/**
 *
 * @author TUNGND
 */
public class HoaDonView extends javax.swing.JFrame {

    Nhanvien nhanvien;
    NhaCungCap nhaCungCap;
    HoaDonDAO hoaDonDAO;
    List<HoadonLinhkien> slist;
    DefaultTableModel model;
    int selected;

    /**
     * Creates new form Customer View
     */
    public HoaDonView(Nhanvien nv, NhaCungCap ncc, List<HoadonLinhkien> listHoadonLinhkien) {
        initComponents();
        nhanvien = nv;
        nhaCungCap = ncc;
        slist = listHoadonLinhkien;
        hoaDonDAO = new HoaDonDAO();

        jLabelGetNCC.setText(nhaCungCap.getTen());
        jLabelGetDiaChi.setText(nhaCungCap.getDiaChi());
        jLabelGetDienThoai.setText(nhaCungCap.getDienThoai());
        jLabelGetNV.setText(nhanvien.getTen());
        this.jButtonRemove.setVisible(false);

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime now = LocalDateTime.now();
        this.jLabelGetThoiGian.setText(dtf.format(now));

        if (slist.isEmpty()) {
            this.jLabelTongTien.setVisible(false);
            this.jLabelGetTongTien.setVisible(false);
        } else {
            this.jLabelTongTien.setVisible(true);
            this.jLabelGetTongTien.setVisible(true);
            Float tongTien = 0.0f;
            model = (DefaultTableModel) this.jTableNCC.getModel();
            model.setRowCount(0);
            for (HoadonLinhkien item : slist) {
                tongTien += item.getThanhTien();
                model.addRow(new Object[]{
                    item.getMa(), item.getTen(), item.getHang(), item.getDonGia(), item.getSoLuong(), item.getThanhTien()
                });
            }
            this.jLabelGetTongTien.setText(String.valueOf(tongTien));
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNCC = new javax.swing.JLabel();
        jLabelDiaChi = new javax.swing.JLabel();
        jLabelDienThoai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNCC = new javax.swing.JTable();
        jButtonInHoaDon = new javax.swing.JButton();
        jLabelGetNCC = new javax.swing.JLabel();
        jLabelGetDiaChi = new javax.swing.JLabel();
        jLabelGetDienThoai = new javax.swing.JLabel();
        jButtonThemLinhKien = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelNV = new javax.swing.JLabel();
        jLabelGetNV = new javax.swing.JLabel();
        jLabelTongTien = new javax.swing.JLabel();
        jLabelGetTongTien = new javax.swing.JLabel();
        jButtonRemove = new javax.swing.JButton();
        jLabelThoiGian = new javax.swing.JLabel();
        jLabelGetThoiGian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNCC.setText("Nhà cung cấp:");

        jLabelDiaChi.setText("Địa chỉ:");

        jLabelDienThoai.setText("Số điện thoại:");

        jTableNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Hãng", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNCC);
        if (jTableNCC.getColumnModel().getColumnCount() > 0) {
            jTableNCC.getColumnModel().getColumn(0).setResizable(false);
            jTableNCC.getColumnModel().getColumn(1).setResizable(false);
            jTableNCC.getColumnModel().getColumn(2).setResizable(false);
            jTableNCC.getColumnModel().getColumn(3).setResizable(false);
            jTableNCC.getColumnModel().getColumn(4).setResizable(false);
            jTableNCC.getColumnModel().getColumn(5).setResizable(false);
        }

        jButtonInHoaDon.setText("In hoá đơn");
        jButtonInHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInHoaDonActionPerformed(evt);
            }
        });

        jLabelGetNCC.setText("ncc");

        jLabelGetDiaChi.setText("dc");

        jLabelGetDienThoai.setText("sdt");

        jButtonThemLinhKien.setText("Thêm linh kiện");
        jButtonThemLinhKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemLinhKienActionPerformed(evt);
            }
        });

        jButtonBack.setText("Quay lại");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelNV.setText("Nhân viên:");

        jLabelGetNV.setText("nv");

        jLabelTongTien.setText("Tổng tiền:");

        jLabelGetTongTien.setText("0");

        jButtonRemove.setText("Xoá");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jLabelThoiGian.setText("Thời gian:");

        jLabelGetThoiGian.setText("time");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDiaChi)
                            .addComponent(jLabelNCC)
                            .addComponent(jLabelThoiGian))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelGetNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                    .addComponent(jLabelGetDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelDienThoai)
                                        .addGap(16, 16, 16))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelNV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelGetNV, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGetDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelGetThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRemove)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonThemLinhKien))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelTongTien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelGetTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 22, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNCC)
                    .addComponent(jLabelDienThoai)
                    .addComponent(jLabelGetNCC)
                    .addComponent(jLabelGetDienThoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGetNV, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDiaChi)
                        .addComponent(jLabelGetDiaChi)
                        .addComponent(jLabelNV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThoiGian)
                    .addComponent(jLabelGetThoiGian))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTongTien)
                    .addComponent(jLabelGetTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonThemLinhKien)
                    .addComponent(jButtonInHoaDon)
                    .addComponent(jButtonRemove)
                    .addComponent(jButtonBack))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInHoaDonActionPerformed
        // TODO add your handling code here:
        if (slist.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng thêm ít nhất một linh kiện");
        } else {
            int input = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn in hoá đơn?");
            if (input == 0) {
                int status = hoaDonDAO.createHoaDon(nhanvien.getID(), nhaCungCap.getID(), slist);
                if (status == 0) {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi");
                } else {
                    JOptionPane.showMessageDialog(this, "Đã thêm vào cơ sở dữ liệu");
                    this.setVisible(false);
                    HomePageView homePageView = new HomePageView(nhanvien);
                    homePageView.setVisible(true);
                    homePageView.setTitle("Hệ thống quản lý gara ô tô");
                }
            }
        }
    }//GEN-LAST:event_jButtonInHoaDonActionPerformed

    private void jTableNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNCCMouseClicked
        // TODO add your handling code here:
        int index = jTableNCC.getSelectedRow();
        selected = index;
        this.jButtonRemove.setVisible(true);
    }//GEN-LAST:event_jTableNCCMouseClicked

    private void jButtonThemLinhKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemLinhKienActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SearchLinhKienView searchLinhKienView = new SearchLinhKienView(nhanvien, nhaCungCap, slist);
        searchLinhKienView.setVisible(true);
        searchLinhKienView.setTitle("Linh kiện");
    }//GEN-LAST:event_jButtonThemLinhKienActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SearchNhaCungCaprView searchCustomerView = new SearchNhaCungCaprView(nhanvien);
        searchCustomerView.setVisible(true);
        searchCustomerView.setTitle("Nhà cung cấp");
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        // TODO add your handling code here:
        slist.remove(selected);
        this.jButtonRemove.setVisible(false);
        if (slist.isEmpty()) {
            this.jLabelTongTien.setVisible(false);
            this.jLabelGetTongTien.setVisible(false);
        } else {
            this.jLabelTongTien.setVisible(true);
            this.jLabelGetTongTien.setVisible(true);
        }
        Float tongTien = 0.0f;
        model = (DefaultTableModel) this.jTableNCC.getModel();
        model.setRowCount(0);
        for (HoadonLinhkien item : slist) {
            tongTien += item.getThanhTien();
            model.addRow(new Object[]{
                item.getMa(), item.getTen(), item.getHang(), item.getDonGia(), item.getSoLuong(), item.getThanhTien()
            });
        }
        this.jLabelGetTongTien.setText(String.valueOf(tongTien));
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonView(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonInHoaDon;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JButton jButtonThemLinhKien;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelDienThoai;
    private javax.swing.JLabel jLabelGetDiaChi;
    private javax.swing.JLabel jLabelGetDienThoai;
    private javax.swing.JLabel jLabelGetNCC;
    private javax.swing.JLabel jLabelGetNV;
    private javax.swing.JLabel jLabelGetThoiGian;
    private javax.swing.JLabel jLabelGetTongTien;
    private javax.swing.JLabel jLabelNCC;
    private javax.swing.JLabel jLabelNV;
    private javax.swing.JLabel jLabelThoiGian;
    private javax.swing.JLabel jLabelTongTien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNCC;
    // End of variables declaration//GEN-END:variables
}
